# File managed by pluginsync
sudo: true
language: go
go:
- 1.6.x
- 1.7.x
env:
  global:
  - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
  - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  matrix:
  - TEST_TYPE=small
  - SNAP_VERSION: latest
    TEST_TYPE: large
  - SNAP_VERSION: latest_build
    TEST_TYPE: large
  - TEST_TYPE=build
matrix:
  exclude:
  - go: 1.6.x
    env: SNAP_VERSION=latest TEST_TYPE=large
  - go: 1.6.x
    env: SNAP_VERSION=latest_build TEST_TYPE=large
  - go: 1.6.x
    env: TEST_TYPE=build
before_install:
- "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"
install:
- cd $SNAP_PLUGIN_SOURCE
- make deps
script:
- make check 2>&1
notifications:
  email: false
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=
before_deploy:
- "./scripts/pre_deploy.sh"
deploy:
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: ftSr5yhNzj0tLQYvB7PklPDBFrWYtqn+G06r0uh/tEFz2+TxGlGP7GdFgiE5OeIADy3NDcG/RcsRkBCVBc2dAKduGMMEeaSjvQ/ukjPDpd6qo5yGK20yOctXD03OLnI3R5Xf3B8D6aNzz1/9xZujfZzI0t+dtDluB2I8GG0xAwDDZXFuQCFJJHGdk7dTCjBKeUE4xOKPCmQB+NlR2hyp8YA5f8ZiYBJhX/aPKBO4H78xHVrVID02Pf1FX7MvxLgFYCRF3M6+xMTH+Ln/PUHlQmUkwoYXy+5z67v+QAKd5WcHB9bzmf90Y1HOS0/Npz5eL6f8UBtNz1q1mlNpWZTdvYzgEOKHutjLtiU7DhgbcRWeXxTTQFzjyTZRmnxATEiSs2j2bVcTKSVvmWX9BwcBu+WjC8S4rDUXLVkyHnUjRSd9EjDi1yNmxJKG5obE9wH51+PQAjaGq3qtE8yN6g4PvMoAOFy5zt7T+AJh+kdcPB8oIsjRylt/tlp5oCo7zB/pP211XGpokKL9eVfRPkZ7Jce+yJ5zPoXxH3/RQDtruXLlb2trVuEbVKmLBrRxkgwRp1hA8DVmNj8U6gg8gSIpLRZZNaaHFkqbL4wum4XyBj8hBE4+Gw/EyN4YdqlVwiD/uhMbIvmQ69Xvg+gwC85MmgJnYNQ64H8H0AT45AdnGI0=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-publisher-graphite
    branch: master
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION =~ ^1\.7\.[0-9]+$
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: ftSr5yhNzj0tLQYvB7PklPDBFrWYtqn+G06r0uh/tEFz2+TxGlGP7GdFgiE5OeIADy3NDcG/RcsRkBCVBc2dAKduGMMEeaSjvQ/ukjPDpd6qo5yGK20yOctXD03OLnI3R5Xf3B8D6aNzz1/9xZujfZzI0t+dtDluB2I8GG0xAwDDZXFuQCFJJHGdk7dTCjBKeUE4xOKPCmQB+NlR2hyp8YA5f8ZiYBJhX/aPKBO4H78xHVrVID02Pf1FX7MvxLgFYCRF3M6+xMTH+Ln/PUHlQmUkwoYXy+5z67v+QAKd5WcHB9bzmf90Y1HOS0/Npz5eL6f8UBtNz1q1mlNpWZTdvYzgEOKHutjLtiU7DhgbcRWeXxTTQFzjyTZRmnxATEiSs2j2bVcTKSVvmWX9BwcBu+WjC8S4rDUXLVkyHnUjRSd9EjDi1yNmxJKG5obE9wH51+PQAjaGq3qtE8yN6g4PvMoAOFy5zt7T+AJh+kdcPB8oIsjRylt/tlp5oCo7zB/pP211XGpokKL9eVfRPkZ7Jce+yJ5zPoXxH3/RQDtruXLlb2trVuEbVKmLBrRxkgwRp1hA8DVmNj8U6gg8gSIpLRZZNaaHFkqbL4wum4XyBj8hBE4+Gw/EyN4YdqlVwiD/uhMbIvmQ69Xvg+gwC85MmgJnYNQ64H8H0AT45AdnGI0=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-publisher-graphite
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION =~ ^1\.7\.[0-9]+$
- provider: releases
  api_key:
    secure: q45immTR0cs6f6+iEhO51LDHdtJ3UJzMZ+1zq74KiTj5Brcuky9iSwQ76Ek7h8byO4KE/tu1YxJwtXiCYxLUVEKC5gCsjE26GO3RMintn0iX+iw57yxu0HtqY759qJn5PS2ptJgikduS3kDyEFS00JgXZ/6pyu3U+BCmLxh0rsoiQFh1oZbI7smkkCH4gZBXyRJZ40PV2V6lKQ4bV/E0fJfqdmZ1P+XiR4em1mkDDW5Sg18MHx1/fv/UoEubUaQsQnP6QZQJoNPId/G53MmnKHvZ+RJIWV3h94N7OJrUZLqKzXzTk5tOtcLf1Namre/RtQrpyCfuQgwBAtU0qM+ADEqCgE+DlOeHxKSbrS0B75eaAbiD1od6iNi3qJx1ljCfH2S2kwQ45lYGNeW9Gu+c8KLWm1h7BNOfAg1cq9q5jJAARytkfFbjAJpg7+eXu30cmVCvuHVxnAWo4U+7GSf03rrKoiOx+x31fK/RARbG/nxS4JAbZjprUc7xKS5eQrspu7+kZ8SqZ24SmJU9qyHD4VtzMJrgE+t9q9Li6qnk+wZbH5ZZpPSHGECAJtfn9nI+qz2R9ODr3DUex1zE/rerCUomp4sqoZMkMTWP+4ypUJ9eZk1z3l1RHB7bA5YkIB73E+jOMLiJUIF1lHhWzNFmw9jSrYQZjIo4j+5JPruZ12Q=
  file:
    - release/snap-plugin-publisher-graphite_linux_x86_64
    - release/snap-plugin-publisher-graphite_darwin_x86_64
  skip_cleanup: true
  on:
    repo: intelsdi-x/snap-plugin-publisher-graphite
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION =~ ^1\.7\.[0-9]+$
